### ISSUE TITLE
"modal-dialog" - css class missing 

### ISSUE THREAD

**Issue by PhilippRoessner** [shlomiassaf/angular2-modal#62] opened 2016-04-24 14:08 UTC
The parent element of 
`<div class="modal-content">...</div>`
Should have two classes, one for the modal-size (modal-lg for example) and a "modal-dialog" class. The second class is missing when I use angular2-modals or custom-modals.

Also the Backdrop is not visible, maybe for the same reason?

**Comment by nmarsman** [comment] 2016-04-29 09:25
+1

**Comment by shlomiassaf** [comment] 2016-05-17 11:42
Is this still relevant is 1.0.0?

**Comment by PhilippRoessner** [comment] 2016-05-17 15:03
Sorry, I can't tell. I switched to primeng - modal. It fits better with the concept of our App.

**Comment by shlomiassaf** [comment] 2016-05-17 17:48
👍 
Great, I will close this then.

**Closed by shlomiassaf** 2016-05-17 17:48 UTC
Labels: need more info

**Comment by DesHorsley** [comment] 2017-01-17 10:02
I can confirm this is still an issue.

I've replicated it in a fork of the plunker supplied in Custom Modal Dialog Sample code, updated to 2.0.2

https://embed.plnkr.co/NJc3lC/

The line which causes the issue is in app.component.ts:55

**Comment by DesHorsley** [comment] 2017-01-23 09:23
Any plans to reopen this ticket @shlomiassaf ?

**Comment by shripalsoni04** [comment] 2017-02-08 21:12
@DesHorsley , I also experienced the same problem that class `modal-dialog` is missing in parent `div` of `<div class="modal-content">` and due to that modal is getting expanded to the full width of the screen.

I tried to looked into the code..and as a workaround I am able to add the classes using below code... 

```
this.modal.open(CustomComponent, overlayConfigFactory({dialogClass: 'modal-dialog modal-sm'}, null, {injector: this.injector}));
```

I am not sure if this is a correct way or not..@shlomiassaf , it will be great if you can guide us regarding this.

Thanks

**Comment by ozknemoy** [comment] 2017-05-15 15:47
same story. @shripalsoni04 `s method works fine  but it kills closing backdrop by click
