### ISSUE TITLE
Error when closing modal

### ISSUE THREAD

**Issue by LeResKP** [shlomiassaf/angular2-modal#184] opened 2016-09-07 14:49 UTC
Your 2 plunkers already show the issue:
  * V1: http://plnkr.co/edit/hwbmF9?p=preview 
  * V2: http://plnkr.co/edit/7c0pGE?p=preview

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
When closing the modal using the button or the escape key, there is an exception in the console:
EXCEPTION: Error: Uncaught (in promise): undefined

* **What is the expected behavior?**
It doesn't break the angular nor the js stack but it's not great to have an exception.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc{5,6}
- Browser:Chrome Version 53.0.2785.92 (64-bit)

**Comment by tomzilla** [comment] 2016-09-13 03:54
seeing same. rc6

**Comment by shlomiassaf** [comment] 2016-09-23 12:24
Duplicate of #188

**Closed by shlomiassaf** 2016-09-23 12:24 UTC
