### ISSUE TITLE
AOT fails 

### ISSUE THREAD

**Issue by harshalpatel91** [shlomiassaf/angular2-modal#281] opened 2017-01-11 11:03 UTC
Hey folks,

Getting following error will compiling with ngc
Error: Error encountered resolving symbol values statically. Could not resolve angular2-modal relative to .../node_modules/angular2-modal/plugins/bootstrap/modal-context.d.ts.

Can any one looks into this.

Regards,

**Comment by shlomiassaf** [comment] 2017-01-11 19:44
Duplicate of #273

I

**Closed by shlomiassaf** 2017-01-11 19:44 UTC
