### ISSUE TITLE
Build prod has a problem angular2-modal version 3.0.1

### ISSUE THREAD

**Issue by hoangminhviet** [shlomiassaf/angular2-modal#370] opened 2017-06-28 03:30 UTC
Hi,
I have a problem when i do run build: prod. 
<img width="372" alt="screen shot 2017-06-28 at 10 26 06 am" src="https://user-images.githubusercontent.com/11186990/27619431-6f643016-5bec-11e7-857f-a5c1fd5ef965.png">
I'm use angular 4. my source in base on this githup [https://github.com/AngularClass/angular-starter](url). I have just do "import {Modal, BSModalContext} from 'angular2-modal/plugins/bootstrap';" in app.component.ts. and then I do run build : prod command line. I got this issue.
Plz suggest to me how to fix it. 
Thank you.

**Comment by shlomiassaf** [comment] 2017-06-30 05:36
dupe of #369

**Closed by shlomiassaf** 2017-06-30 05:36 UTC
