### ISSUE TITLE
About the "Known issue - DI exception"

### ISSUE THREAD

**Issue by bertvh** [shlomiassaf/angular2-modal#19] opened 2016-01-25 18:30 UTC
I've been using the modal for a few weeks now and I'm pretty happy with it. Great work!

However, the DI-know issue that requires us to add this kind of code ...

``` typescript
return Injector.resolve([
      provide(DynamicComponentLoader, {useValue: this.injector.get(DynamicComponentLoader)}),
      provide(ICustomModal, {useValue: new WizardModalContent(...),
      provide(IterableDiffers, {useValue: this.injector.get(IterableDiffers)}),
      provide(KeyValueDiffers, {useValue: this.injector.get(KeyValueDiffers)}),
      provide(Renderer, {useValue: this._renderer}),
      provide(MyService, {useValue: this.injector.get(MyService}), 
      provide(/*whatvever the component you put in the modal (or ANY of it's subcomponents need*/) 
    ]);
```

... combined with the fact that those components apparently can't declare this ... 

``` typescript
@Component({
    providers: [MyService]
})
```

... because that crashes a well. And that of course an issue that will bite me real hard one I reuse that component in a non-modal context :(

Do you think think this can all be solved by fixing [angular/angular#4330](https://github.com/angular/angular/issues/4330)? If so, maybe we should breathe some more life into this issue!

**Comment by shlomiassaf** [comment] 2016-03-05 19:43
Sorry for the delay, since the issue is fixed now, can you see if the fix solved your issues?

**Comment by bertvh** [comment] 2016-03-07 09:24
Unfortunately, I can't test this quickly. I've tried updating to beta6 a few days ago but this breaks so much (on our app) that I gave up. Will give it another try in a few weeks.

**Comment by shlomiassaf** [comment] 2016-04-12 22:01
I'll close this stale issue, please re-open with a comment if it still an issue.

**Closed by shlomiassaf** 2016-04-12 22:01 UTC
